# Generated by Django 3.2.7 on 2023-12-07 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_job_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 7, 9, 36, 36, 761890)),
        ),
    ]
